parameters:
    netgen.ezforms.form.fieldtype_handler.ezimage.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Image
    netgen.ezforms.form.fieldtype_handler.ezstring.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\TextLine
    netgen.ezforms.form.fieldtype_handler.eztext.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\TextBlock
    netgen.ezforms.form.fieldtype_handler.ezuser.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\User
    netgen.ezforms.form.fieldtype_handler.ezemail.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Email
    netgen.ezforms.form.fieldtype_handler.ezselection.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Selection
    netgen.ezforms.form.fieldtype_handler.ezboolean.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Checkbox
    netgen.ezforms.form.fieldtype_handler.ezdate.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Date
    netgen.ezforms.form.fieldtype_handler.ezdatetime.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\DateAndTime
    netgen.ezforms.form.fieldtype_handler.ezinteger.class: Netgen\Bundle\EzFormsBundle\Form\FieldTypeHandler\Integer

services:
    netgen.ezforms.form.fieldtype_handler.ezimage:
        class: %netgen.ezforms.form.fieldtype_handler.ezimage.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezimage}

    netgen.ezforms.form.fieldtype_handler.ezstring:
        class: %netgen.ezforms.form.fieldtype_handler.ezstring.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezstring}

    netgen.ezforms.form.fieldtype_handler.eztext:
        class: %netgen.ezforms.form.fieldtype_handler.eztext.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: eztext}

    netgen.ezforms.form.fieldtype_handler.ezuser:
        class: %netgen.ezforms.form.fieldtype_handler.ezuser.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezuser}

    netgen.ezforms.form.fieldtype_handler.ezemail:
        class: %netgen.ezforms.form.fieldtype_handler.ezemail.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezemail}

    netgen.ezforms.form.fieldtype_handler.ezselection:
        class: %netgen.ezforms.form.fieldtype_handler.ezselection.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezselection}

    netgen.ezforms.form.fieldtype_handler.ezboolean:
        class: %netgen.ezforms.form.fieldtype_handler.ezboolean.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezboolean}

    netgen.ezforms.form.fieldtype_handler.ezdate:
        class: %netgen.ezforms.form.fieldtype_handler.ezdate.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezdate}

    netgen.ezforms.form.fieldtype_handler.ezdatetime:
        class: %netgen.ezforms.form.fieldtype_handler.ezdatetime.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezdatetime}

    netgen.ezforms.form.fieldtype_handler.ezinteger:
        class: %netgen.ezforms.form.fieldtype_handler.ezinteger.class%
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: ezinteger}
