filter:
    paths:
        - 'bundle/*'
    excluded_paths: 
        - 'tests/*'
        - 'vendor/*'
        - 'build/*'
        - 'doc/*'

checks:
    php: true

tools:
    php_analyzer: true
    sensiolabs_security_checker: true
